name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git openjdk-11-jdk unzip zip wget
        python3 -m pip install --upgrade pip
        pip install buildozer

    - name: Install Android SDK Command-line tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Android SDK and NDK packages
      run: |
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/Android/Sdk/ndk/21.4.7075529" >> $GITHUB_ENV
        echo "ANDROIDAPI=31" >> $GITHUB_ENV
        echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
