name: Build Kivy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -sSLo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q tools.zip -d latest
        rm tools.zip

        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

    - name: Accept licenses and install SDK packages
      run: |
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses <<< "y"
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "build-tools;36.0.0" \
          "platforms;android-31" \
          "ndk;25.1.8937393"

    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: bin/*.apk
