name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git openjdk-17-jdk unzip zip wget
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    
    - name: Install Android SDK and accept licenses
      env:
        ANDROID_SDK_ROOT: $HOME/Android/Sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q tools.zip -d latest
        rm tools.zip

        # Добавим sdkmanager в PATH
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        # Принимаем лицензии и устанавливаем нужные компоненты
        yes | sdkmanager --licenses
        sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;36.0.0" \
          "ndk;25.1.8937393"


    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "$HOME/Android/Sdk/platform-tools" >> $GITHUB_PATH


    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
